name: 🐞 BUG
description: File a bug/issue
title: "[BUG] <title>"
labels: [ "bug" ]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    attributes:
      label: App version
      description: What application version do you use?
    validations:
      required: true
  - type: input
    attributes:
      label: Windows version
      description: What Windows version do you use?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Logs? Screenshots? Anything that will give us more context about the issue you are encountering!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
