name: Feature request
description: Suggest an idea for this project.
labels: [ "enhancement" ]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have used the search function to see if someone else has already submitted the same feature request.
          required: true
        - label: I will describe the problem in as much detail as possible.
          required: true
        - label: This issue only requests one feature, **not** multiple (related) features.
          required: true

